 name: 📚 Documentation Issue
description: Report missing, unclear, or incorrect documentation. Use this if you found a typo, outdated info, or something that could be explained better in the docs.
title: '[Docs]: '
labels: [documentation, needs-triage]
projects: ['NexusDI/3']
body:
  - type: textarea
    attributes:
      label: What's wrong or missing?
      description: Describe the documentation issue or improvement.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Where did you look?
      description: Link to the page or section in question.
  - type: textarea
    attributes:
      label: Suggestion
      description: How could the docs be improved?
