name: Documentation Issue
description: Report a problem or suggest an improvement for the documentation
title: '[Docs]: '
labels: [documentation, needs-triage]
projects: ['NexusDI/3']
body:
  - type: textarea
    attributes:
      label: What’s wrong or missing?
      description: Describe the documentation issue or improvement.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Where did you look?
      description: Link to the page or section in question.
  - type: textarea
    attributes:
      label: Suggestion
      description: How could the docs be improved?
