import { channels } from './contrast.js';
import { colour, surface } from './colour.js';
import { elevation, focus, measure, radius, space } from './geometry.js';
import { exportKinds, kindRole } from './kind.js';
import { lifetimeRole } from './lifetime.js';
import { motion } from './motion.js';
import { family, tracking, type } from './type.js';

/**
 * The token modules rendered as the custom-property block `styles.css`
 * imports. This function is the only producer of `src/tokens.generated.css`.
 */

function kebab(name: string): string {
  return name
    .replace(/([a-z])([A-Z0-9])/g, '$1-$2')
    .replace(/([0-9])([a-z])/g, '$1-$2')
    .toLowerCase();
}

/**
 * The two ground roles (`space0`, `space2`) take a `ground-` property, not
 * the generic `kebab(role)` mapping. The spacing scale already holds
 * `--meridian-space-1` through `--meridian-space-8`; a role named `space2`
 * would otherwise render as `--meridian-space-2` too, and both declarations
 * target `:root`, so one would silently win over the other.
 */
const GROUND_PROPERTY: Partial<Record<string, string>> = {
  space0: '--meridian-ground-0',
  space2: '--meridian-ground-2',
};

function customProperty(role: string): string {
  return GROUND_PROPERTY[role] ?? `--meridian-${kebab(role)}`;
}

function rgba(hex: string, alpha: number): string {
  return `rgb(${channels(hex).join(' ')} / ${alpha})`;
}

type Declaration = readonly [string, string];

function block(selector: string, declarations: readonly Declaration[]): string {
  const body = declarations
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n');
  return `${selector} {\n${body}\n}`;
}

function theme(name: 'dark' | 'light'): Declaration[] {
  return [
    ...Object.entries(colour[name]).map(
      ([role, hex]) => [customProperty(role), hex] as const,
    ),
    ['--meridian-hull', rgba(surface[name].hull.hex, surface[name].hull.alpha)],
    [
      '--meridian-hull-raised',
      rgba(surface[name].hullRaised.hex, surface[name].hullRaised.alpha),
    ],
    ['--meridian-focus', focus[name]],
  ];
}

const shared: Declaration[] = [
  ...Object.entries(colour.dark).map(
    ([role, hex]) => [`--meridian-palette-dark-${kebab(role)}`, hex] as const,
  ),
  ...Object.entries(colour.light).map(
    ([role, hex]) => [`--meridian-palette-light-${kebab(role)}`, hex] as const,
  ),
  ['--meridian-font-display', family.display],
  ['--meridian-font-body', family.body],
  ['--meridian-font-mono', family.mono],
  ...Object.entries(type).flatMap(
    ([step, value]) =>
      [
        [`--meridian-text-${step}`, value.size],
        [`--meridian-leading-${step}`, value.leading],
      ] as const,
  ),
  ['--meridian-tracking-display', tracking.display],
  ['--meridian-tracking-micro', tracking.micro],
  ...Object.entries(space).map(
    ([step, value]) => [`--meridian-space-${step}`, value] as const,
  ),
  ['--meridian-measure', measure],
  ...Object.entries(radius).map(
    ([role, value]) => [`--meridian-radius-${role}`, value] as const,
  ),
  ['--meridian-elevation-glass', elevation.glass],
  ['--meridian-elevation-raised', elevation.raised],
  ['--meridian-motion-interaction', motion.interaction],
  ['--meridian-motion-console', motion.console],
  ['--meridian-motion-curve', motion.curve],
  ...Object.entries(lifetimeRole).map(
    ([lifetime, role]) =>
      [
        `--meridian-lifetime-${lifetime}`,
        `var(${customProperty(role)})`,
      ] as const,
  ),
  ...exportKinds.map(
    (kind) =>
      [
        `--meridian-kind-${kind}`,
        `var(${customProperty(kindRole[kind])})`,
      ] as const,
  ),
];

/** Every custom property, in declaration order, for tests and tooling. */
export const customProperties: readonly Declaration[] = [
  ...shared,
  ...theme('light'),
  ...theme('dark'),
];

/** The contents of `src/tokens.generated.css`, trailing newline included. */
export function renderTokensCss(): string {
  const parts = [
    '/* Generated by tools/generate-tokens.ts from src/tokens/. Do not edit. */',
    block(':root', shared),
    block(':root,\nhtml', theme('light')),
    block('html.dark', theme('dark')),
    [
      '@media (prefers-reduced-motion: reduce) {',
      '  :root {',
      '    --meridian-motion-interaction: 0ms;',
      '    --meridian-motion-console: 0ms;',
      '  }',
      '}',
    ].join('\n'),
    ...exportKinds.map((kind) =>
      block(`.meridian-kind-${kind}`, [
        ['--meridian-kind', `var(--meridian-kind-${kind})`],
      ]),
    ),
  ];

  return `${parts.join('\n\n')}\n`;
}
