name: Commit Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  commitlint:
    name: Lint commits in PR or push
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Lint new commits
        run: |
          npx commitlint --from ${{ github.event.before }} --to ${{ github.sha }}
