name: Docs Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install docs dependencies
        run: npm ci
        working-directory: docs

      - name: Build docs
        run: npm run build
        working-directory: docs

      - name: Deploy docs
        run: npm run deploy
        working-directory: docs
        env:
          GIT_USER: github-actions[bot]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
